// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package startup

import (
	repository2 "github.com/liupch66/basic-go/webook/interact/repository"
	cache2 "github.com/liupch66/basic-go/webook/interact/repository/cache"
	dao2 "github.com/liupch66/basic-go/webook/interact/repository/dao"
	service2 "github.com/liupch66/basic-go/webook/interact/service"
	article3 "github.com/liupch66/basic-go/webook/internal/events/article"
	"github.com/liupch66/basic-go/webook/internal/repository"
	article2 "github.com/liupch66/basic-go/webook/internal/repository/article"
	"github.com/liupch66/basic-go/webook/internal/repository/cache"
	"github.com/liupch66/basic-go/webook/internal/repository/dao"
	"github.com/liupch66/basic-go/webook/internal/repository/dao/article"
	"github.com/liupch66/basic-go/webook/internal/service"
	"github.com/liupch66/basic-go/webook/internal/service/oauth2/wechat"
	"github.com/liupch66/basic-go/webook/internal/web"
	"github.com/liupch66/basic-go/webook/internal/web/jwt"
	"github.com/liupch66/basic-go/webook/ioc"
	"github.com/gin-gonic/gin"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitUserSvc() service.UserService {
	gormDB := InitTestDB()
	userDAO := dao.NewUserDAO(gormDB)
	cmdable := InitRedis()
	userCache := cache.NewUserCache(cmdable)
	userRepository := repository.NewUserRepository(userDAO, userCache)
	loggerV1 := InitLog()
	userService := service.NewUserService(userRepository, loggerV1)
	return userService
}

func InitCodeSvc() service.CodeService {
	cmdable := InitRedis()
	codeCache := cache.NewCodeCache(cmdable)
	codeRepository := repository.NewCodeRepository(codeCache)
	smsService := ioc.InitSmsService(cmdable)
	codeService := service.NewCodeService(codeRepository, smsService)
	return codeService
}

func InitWechatSvc() wechat.Service {
	loggerV1 := InitLog()
	wechatService := ioc.InitWechatService(loggerV1)
	return wechatService
}

func InitInteractService() service2.InteractService {
	gormDB := InitTestDB()
	interactDAO := dao2.NewGORMInteractDAO(gormDB)
	cmdable := InitRedis()
	interactCache := cache2.NewRedisInteractCache(cmdable)
	loggerV1 := InitLog()
	interactRepository := repository2.NewCachedInteractRepository(interactDAO, interactCache, loggerV1)
	interactService := service2.NewInteractService(interactRepository, loggerV1)
	return interactService
}

// 这里注入 artDAO 是为了方便集成测试 GORM DB 和 MongoDB 实现的文章储存
func InitArticleHandler(artDAO article.ArticleDAO) *web.ArticleHandler {
	gormDB := InitTestDB()
	userDAO := dao.NewUserDAO(gormDB)
	cmdable := InitRedis()
	userCache := cache.NewUserCache(cmdable)
	userRepository := repository.NewUserRepository(userDAO, userCache)
	articleCache := cache.NewRedisArticleCache(cmdable)
	loggerV1 := InitLog()
	articleRepository := article2.NewCachedArticleRepository(userRepository, artDAO, articleCache, loggerV1)
	client := InitKafka()
	syncProducer := InitSyncProducer(client)
	producer := article3.NewSaramaSyncProducer(syncProducer)
	articleService := service.NewArticleService(articleRepository, loggerV1, producer)
	interactDAO := dao2.NewGORMInteractDAO(gormDB)
	interactCache := cache2.NewRedisInteractCache(cmdable)
	interactRepository := repository2.NewCachedInteractRepository(interactDAO, interactCache, loggerV1)
	interactService := service2.NewInteractService(interactRepository, loggerV1)
	articleHandler := web.NewArticleHandler(articleService, interactService, loggerV1)
	return articleHandler
}

func InitWebServer() *gin.Engine {
	loggerV1 := InitLog()
	cmdable := InitRedis()
	handler := jwt.NewRedisJwtHandler(cmdable)
	v := ioc.InitMiddlewares(loggerV1, cmdable, handler)
	gormDB := InitTestDB()
	userDAO := dao.NewUserDAO(gormDB)
	userCache := cache.NewUserCache(cmdable)
	userRepository := repository.NewUserRepository(userDAO, userCache)
	userService := service.NewUserService(userRepository, loggerV1)
	codeCache := cache.NewCodeCache(cmdable)
	codeRepository := repository.NewCodeRepository(codeCache)
	smsService := ioc.InitSmsService(cmdable)
	codeService := service.NewCodeService(codeRepository, smsService)
	userHandler := web.NewUserHandler(userService, codeService, handler)
	wechatService := ioc.InitWechatService(loggerV1)
	wechatHandlerConfig := ioc.InitWechatHandlerConfig()
	oAuth2WechatHandler := web.NewOAuth2WechatHandler(wechatService, userService, wechatHandlerConfig, handler)
	articleDAO := article.NewGORMArticleDAO(gormDB)
	articleHandler := InitArticleHandler(articleDAO)
	engine := ioc.InitWebServer(v, userHandler, oAuth2WechatHandler, articleHandler)
	return engine
}

// wire.go:

var (
	thirdPS = wire.NewSet(InitTestDB, InitRedis, InitLog,
		InitKafka, InitSyncProducer, article3.NewSaramaSyncProducer)
	userSvcPS     = wire.NewSet(dao.NewUserDAO, cache.NewUserCache, repository.NewUserRepository, service.NewUserService)
	codeSvcPS     = wire.NewSet(cache.NewCodeCache, repository.NewCodeRepository, ioc.InitSmsService, service.NewCodeService)
	articleSvcPS  = wire.NewSet(article.NewGORMArticleDAO, cache.NewRedisArticleCache, article2.NewCachedArticleRepository, service.NewArticleService)
	wechatSvcPS   = wire.NewSet(ioc.InitWechatService)
	interactSvcPS = wire.NewSet(dao2.NewGORMInteractDAO, cache2.NewRedisInteractCache, repository2.NewCachedInteractRepository, service2.NewInteractService)
)
