#db:
#  dsn: "root:root@tcp(localhost:3306)/webook"

db:
  src:
    dsn: "root:root@tcp(localhost:3306)/webook"
  dst:
    dsn: "root:root@tcp(localhost:3306)/webook_interact"

migrator:
  pattern: "SRC_ONLY"
  http:
    addr: ":8083"

redis:
  addr: "localhost:6379"

kafka:
  addrs:
    - "localhost:9094"

grpc:
  server:
    addr: ":8090"